//Css styles
import styles from "@/styles/dashboard.module.css";

//Framework imports
import { useEffect, useState } from "react";
import Head from "next/head";
import { Card, Layout, Skeleton, Space } from "antd";
import Link from "next/link";

//Custom hooks or apiCall
import { allPost } from "./api";

export async function getServerSideProps() {
  const posts = await allPost();
  return { props: { posts: posts.data } };
}

export default function Dashboard({ posts }) {
  return (
    <>
      <Head>
        <title>Ericsson Case</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Skeleton
        paragraph={{
          rows: 10,
          width: "80%",
        }}
        style={{ margin: "2rem" }}
        active
        loading={!posts}
      >
        <Layout className={styles.dashboardWrapper}>
          <Space
            direction="horizontal"
            size={24}
            className={styles.dashboardContent}
          >
            {posts?.map((post) => (
              <Link key={post.id} href={`/detail/${post.id}`}>
                <Card title={post.title} className={styles.dashboardPost}>
                  <p>{post?.body}</p>
                </Card>
              </Link>
            ))}
          </Space>
        </Layout>
      </Skeleton>
    </>
  );
}
